name = "account-book"
pages_build_output_dir = "public"

# 关键配置：启用Node.js兼容，解决内置模块找不到的问题
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "account-book-db"
database_id = "b2a5243b-8cb8-4a86-88fc-0a057d288f29"

# 环境变量
[vars]
JWT_SECRET = "wjxyyds"
