# 项目名称
name = "account-book"
# 静态文件目录
pages_build_output_dir = "public"

# D1数据库绑定（部署后在CloudFlare后台配置，本地开发用）
[[d1_databases]]
binding = "DB"
database_name = "account-book-db"
database_id = "b2a5243b-8cb8-4a86-88fc-0a057d288f29"

# 环境变量
[vars]
JWT_SECRET = "wjxyyds"
